_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
gamma:
    value: 0.99
learning_rate:
    value: 1e-05
number_of_episodes:
    value: 3000
number_of_rewards_to_average:
    value: 10
target_reward:
    value: 20
